server:
  port: ${PORT:8888}

logging:
  level:
    org.atmosphere: warn

# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
vaadin:
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,com.rubn,com.infraleap,in.viritin
  # Launch the default browser when starting the application in development mode
  launch-browser: true
  copilot:
    enable: false
# Let Hibernate update the schema automatically or create it if it does not exist.
#
# DO NOT DO THIS IN PRODUCTION!
#
# Instead, use Flyway or another controlled way of managing your database schema.
# See https://vaadin.com/docs/latest/building-apps/forms-data/add-flyway for instructions.
spring:
  #jpa:
  #  hibernate:
  #    ddl-auto: update
  servlet:
    multipart.max-file-size: 50MB
    multipart.max-request-size: 50MB

app:
  app-version: 1.0.24-SNAPSHOT
  browser:
    auto-open: true